name: Deploy

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 13.1.0
    - run: yarn install
    - run: yarn build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}      
      with:
        repo: git@github.com:harrybiddle/harrybiddle.github.io.git
        target_branch: master
        build_dir: build/
