name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 15.0.4
    - run: yarn install
    - run: yarn build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      with:
        repo: harrybiddle/harrybiddle.github.io
        fqdn: compdex.rocks
        target_branch: master
        build_dir: build/
