name: Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env: { CI: true }
    steps:
    - uses: actions/checkout@v1
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 15.4.0
    - name: cache dependencies
      uses: actions/cache@v1.0.3
      with:
        path: node_modules/
        key: v1-${{ hashFiles('yarn.lock') }}
    - run: yarn install
    - run: yarn export

