name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 13.1.0
    - name: Install, build, and test
      run: |
        yarn install
        yarn build
        yarn test
    
